### PR TITLE
fixes for MSVC 14.1, aka VS 2017

### PR DESCRIPTION
**Pull request by ra1nb0w**
- new option BUILD_TOOL to enable dsdccx tool (always on)
- remove CXX_FLAGS not compatible with MSVC
- move project ahead to avoid compiler discovery failure

### CODE REVIEW

**Comment by ra1nb0w** [comment]
ping

**Comment by ra1nb0w** [comment]
thank you

**Comment by ra1nb0w** [comment]
where is gone?

**Comment by f4exb** [comment]
Some mish-mash with git push. I have tried to reinstate it from the PR diff.

**Comment by ra1nb0w** [comment]
your commit is wrong.
no `option` and wrong position `if(BUILD_TOOL)`
see https://patch-diff.githubusercontent.com/raw/f4exb/dsdcc/pull/23.patch

**Comment by f4exb** [comment]
Applied your patch. Commit a0f4694

**Pull request merged**
